# Understand kernl/windows/filters

In [24]:
import cv2
import numpy as np

kernel = np.ones((3,3),np.float32)/9
print(kernel)
dst = cv2.filter2D(img,-1,kernel)#src , depth , kernal

[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]


# 1. Image filtering using 2D convolution 

In [9]:
import cv2
import numpy as np
import matplotlib. pyplot as pit

#Load the image here
img = cv2.imread('D:\\Education\\IUP\\Lab6\\saltandpepper1.png.' , 1)

kernel = np.ones((5,5),np.float32)/25
print(kernel)
dst = cv2.filter2D(img,-1,kernel)#src , depth (unchanged original img -> -1 ) , kernal

result = np.hstack((img,dst))
cv2.imshow('result',result)

cv2.waitKey(0)

[[0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]]


-1

# 2. Image Averaging using Box Filter

In [20]:
#Load the image here
img1 = cv2.imread('D:\\Education\\IUP\\Lab6\\saltandpepper1.png.' , 1)

blur = cv2.blur(img1,(5,5) )#src , ksize

result = np.hstack((img1,blur))
cv2.imshow('result',result)

cv2.waitKey(0)

-1

In [27]:
#Load the image here
img2 = cv2.imread('D:\\Education\\IUP\\Lab6\\saltandpepper2.png' , 1)

box = cv2.boxFilter(img2,-1, (5,5) )#src , depth , ksize

result = np.hstack((img2,box))
cv2.imshow('result',result)

cv2.waitKey(0)

-1

# 3. Median Filtering and Gaussian Filtering 

In [28]:
#Load the image here
img3 = cv2.imread('D:\\Education\\IUP\\Lab6\\saltandpepper2.png' , 1)

median = cv2.medianBlur(img3,3)

result = np.hstack((img3,median))
cv2.imshow('result',result)

cv2.waitKey(0)

-1

In [32]:
#Load the image here
img4 = cv2.imread('D:\\Education\\IUP\\Lab6\\gaussian Noise.png' , 1)

gaussian = cv2.GaussianBlur(img4, (11,11),0)#src , ksize (kernel) , standered dwviation sigmax
result = np.hstack((img4,gaussian))
cv2.imshow('result',result)

cv2.waitKey(0)

-1

# 4. Application of image blurring

In [ ]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
#Load the image here
img5 = cv2.imread('D:\\Education\\IUP\\Lab6\\hubble.png' , 1)

#Create custom kernaL of size 15x15 and apply to the input image
kernel = np.ones((15,15), np.float32) / 225 
print(kernel)
dst = cv2.filter2D(img5, -1, kernel)

#AppLy thresholding operator to highlight the largest object
ret, thresh = cv2.threshold(dst, 100, 255, cv2.THRESH_BINARY)

result = np.hstack((img5,dst,thresh))
cv2 .imshow('result' ,result)
cv2 .waitKey(0)